##Docker compose para python y postgres
#https://docs.docker.com/compose/django/
version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: DB_N_REYNAS
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #networks:
    #  app_network:
    #    - ipv4_address: 172.16.1.1
  web:
    build: .
    container_name: FLASK_N_REYNAS
    env_file:
      - web.env
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    #networks:
    #  app_network:
    #    - ipv4_address: 172.16.1.2



#networks:
#  app_network:
#    ipam:
#      config:
#        - subnet: 172.16.1.0/16
volumes:
  db-data:
