##Docker compose para python y postgres
#https://docs.docker.com/compose/django/
version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: DB_N_REYNAS
    env_file:
      - ./app/config/db.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    entrypoint: ["python", "-m", "flask", "run", "--host=0.0.0.0"]
    container_name: FLASK_N_REYNAS
    env_file:
      - ./app/config/web.env
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db-data:
